sudo: required
language: go

env:
  - ARCH=x86
  - ARCH=arm64

services:
  - docker

go:
  - 1.11.x

env:
  - TEST_SUITE=test-unit
  - TEST_SUITE=test-bogo
  - TEST_SUITE=test-interop

matrix:
  fast_finish: true

before_install:
  - make -f _dev/Makefile fmtcheck

install:
  - sudo pip install docker

script:
  - make -f _dev/Makefile build-all && make -f _dev/Makefile "$TEST_SUITE"
